apply plugin: "java-library"

jar {
    enabled = true
}

dependencies {
    /*******************************
     * API Dependencies
     *******************************/

    /*******************************
     * Compile Only Dependencies
     *******************************/

    compileOnly("com.google.code.findbugs:annotations")
    compileOnly("org.apache.hbase:hbase-annotations")
    compileOnly("org.apache.yetus:audience-annotations:0.13.0")

    /*******************************
     * Implementation Dependencies
     *******************************/

    implementation(project(':pxf-api'))
    implementation("com.google.protobuf:protobuf-java")
    implementation("commons-collections:commons-collections")
    implementation("org.apache.hbase:hbase-client")                  { transitive = false }
    implementation("org.apache.hbase:hbase-common")                  { transitive = false }
    implementation("org.apache.hbase:hbase-protocol")                { transitive = false }
    implementation("org.apache.hbase:hbase-protocol-shaded")         { transitive = false }
    implementation("org.apache.hbase.thirdparty:hbase-shaded-protobuf:4.1.13") { transitive = false }
    implementation("org.apache.hbase.thirdparty:hbase-unsafe:4.1.13") { transitive = false }
    implementation("org.apache.zookeeper:zookeeper")                 { transitive = false }
    implementation("io.netty:netty-common")                          { transitive = false }
    implementation("io.netty:netty-transport")                       { transitive = false }

    implementation("org.springframework.boot:spring-boot-starter-log4j2")

    /*******************************
     * Test Dependencies
     *******************************/

    testCompileOnly("com.google.code.findbugs:annotations")
    testCompileOnly("org.apache.hbase:hbase-annotations")
    testCompileOnly("org.apache.yetus:audience-annotations:0.13.0")
    testImplementation("com.esotericsoftware:minlog")
    testImplementation("com.esotericsoftware:reflectasm")
    testImplementation('org.springframework.boot:spring-boot-starter-test')
}

test {
    useJUnitPlatform()
}
